environmental = {
    "exact_unigrams": {"epa", "ghg"},
    "exact_bigrams": {
        "climate change",
        "global warming",
        "clean energy",
        "renewable energy",
        "fossil fuel",
        "fossil fuels",
        "greenhouse gas",
        "greenhouse gases",
        "clean air",
        "clean water",
        "paris accord",
        "paris agreement",
        "carbon tax",
        "cap and trade",
        "sea level",
        "sea levels",
        "wind energy",
        "wind power",
        "solar energy",
        "oil spill",
        "carbon dioxide",
        "carbon emission",
        "carbon emissions",
    },
    "p2": {},
    "p3": {},
    "p4": {"kyot"},
    "p5": {"envir", "emiss", "solar", "ozone"},
    "p6": {"pollut", "carbon", "climat", "fossil", "recycl"},
    "p7": {"ecologi", "sustain", "biodive", "contami", "wildlif"},
    "p8": {"renewabl", "emission"},
    "p9": {"greenhous", "conservat"},
    "p10": {"sustainabl", "renewablen"},
    "p11": {},
    "seven_letter_exclude": {"climati", "politic", "sustain"},
}
