#!/usr/bin/env python
"""
Review no_match suggestions from the matching pipeline.

This script reads the no_match suggestions CSV generated by match_politicians_hs_to_hs_all_clean.py
and allows review of candidates before integration.

Usage:
    python review_and_integrate_suggestions.py [--output OUTPUT_PATH]
"""

import argparse
from pathlib import Path
from difflib import SequenceMatcher
import sys

import polars as pl

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from source.match_politicians_hs_to_hs_all_clean import (
    clean_hs_reference,
    normalize_city,
    normalize_school_name,
    normalize_state,
    project_root,
)


def load_suggestions(suggestions_path: str) -> pl.DataFrame:
    """Load the no_match suggestions CSV."""
    if not Path(suggestions_path).exists():
        return pl.DataFrame(
            schema={
                "bioguide": pl.Utf8,
                "politician_name": pl.Utf8,
                "hs_name": pl.Utf8,
                "hs_city": pl.Utf8,
                "hs_state": pl.Utf8,
                "suggestion_rank": pl.Int64,
                "suggestion_score": pl.Float64,
                "school_id": pl.Utf8,
                "school_name": pl.Utf8,
                "school_street": pl.Utf8,
                "school_city": pl.Utf8,
                "school_state": pl.Utf8,
                "school_zip": pl.Utf8,
                "school_county_name": pl.Utf8,
            }
        )
    df = pl.read_csv(suggestions_path)
    return df


def load_matched_results(results_path: str) -> pl.DataFrame:
    """Load the matched results CSV."""
    df = pl.read_csv(results_path)
    return df


def load_school_reference(reference_path: str) -> pl.DataFrame:
    """Load and normalize the school reference table."""
    df = pl.read_csv(
        reference_path,
        null_values=["NA", "", "N", "M"],
        schema_overrides={
            "school_id": pl.Utf8,
            "state_fips": pl.Utf8,
            "county_fips": pl.Utf8,
            "zip": pl.Utf8,
            "sldl": pl.Utf8,
            "sldu": pl.Utf8,
            "school_year": pl.Utf8,
            "school_type": pl.Utf8,
        },
        infer_schema_length=10000,
    )
    if "school_type" not in df.columns and "source" in df.columns:
        df = df.rename({"source": "school_type"})
    return clean_hs_reference(df)


def build_politician_name(df_matched: pl.DataFrame) -> pl.DataFrame:
    """Create a politician_name column from matched results."""
    return df_matched.with_columns(
        pl.concat_str(
            [
                pl.col("first_name").fill_null(""),
                pl.col("middle_name").fill_null(""),
                pl.col("last_name").fill_null(""),
            ],
            separator=" ",
        )
        .str.replace_all(r"\s+", " ")
        .str.strip_chars()
        .alias("politician_name")
    )


def enrich_suggestions_with_politician_name(
    df_suggestions: pl.DataFrame,
    df_matched: pl.DataFrame,
) -> pl.DataFrame:
    """Attach politician name information to suggestion rows."""
    df_names = build_politician_name(df_matched).select(["bioguide", "politician_name"])
    return df_suggestions.join(df_names, on="bioguide", how="left")


def get_current_no_match_rows(df_matched: pl.DataFrame) -> pl.DataFrame:
    """Return the current no_match rows from the latest matched results."""
    return (
        build_politician_name(df_matched)
        .with_row_index("review_id")
        .with_columns(
            normalize_school_name(pl.col("hs_name")).alias("hs_name_norm"),
            normalize_city(pl.col("hs_city")).alias("hs_city_norm"),
            normalize_state(pl.col("hs_state")).alias("hs_state_abbr"),
        )
        .filter(pl.col("match_method") == "no_match")
        .select([
            "review_id",
            "bioguide",
            "politician_name",
            "hs_name",
            "hs_city",
            "hs_state",
            "hs_name_norm",
            "hs_city_norm",
            "hs_state_abbr",
        ])
    )


def similarity_ratio(a: str, b: str) -> float:
    return SequenceMatcher(None, a, b).ratio()


def generate_no_match_suggestions(
    df_no_match: pl.DataFrame,
    df_hs_ref: pl.DataFrame,
    top_k: int = 3,
    min_score: float = 0.72,
) -> pl.DataFrame:
    ref_cols = [
        "school_id",
        "school_name",
        "street",
        "city",
        "state",
        "zip",
        "county_name",
        "school_name_norm",
        "school_city_norm",
        "school_state_abbr",
    ]
    ref_rows = df_hs_ref.select(ref_cols).to_dicts()

    by_state: dict[str, list[dict[str, str]]] = {}
    for row in ref_rows:
        state_key = row.get("school_state_abbr")
        if state_key is not None:
            by_state.setdefault(state_key, []).append(row)

    out_rows: list[dict[str, object]] = []
    for rec in df_no_match.to_dicts():
        hs_name_norm = rec.get("hs_name_norm") or ""
        hs_city_norm = rec.get("hs_city_norm") or ""
        hs_state_abbr = rec.get("hs_state_abbr")

        if not hs_name_norm:
            continue

        pool = by_state.get(hs_state_abbr, ref_rows) if hs_state_abbr else ref_rows
        scored: list[tuple[float, dict[str, str]]] = []

        for cand in pool:
            cand_name = cand.get("school_name_norm") or ""
            if not cand_name:
                continue
            name_score = similarity_ratio(hs_name_norm, cand_name)
            city_score = similarity_ratio(hs_city_norm, cand.get("school_city_norm") or "") if hs_city_norm else 0.0
            state_bonus = 0.10 if hs_state_abbr and hs_state_abbr == cand.get("school_state_abbr") else 0.0
            score = 0.8 * name_score + 0.2 * city_score + state_bonus
            if score >= min_score:
                scored.append((score, cand))

        scored.sort(key=lambda x: x[0], reverse=True)
        for rank, (score, cand) in enumerate(scored[:top_k], start=1):
            out_rows.append(
                {
                    "review_id": rec.get("review_id"),
                    "bioguide": rec.get("bioguide"),
                    "politician_name": rec.get("politician_name"),
                    "hs_name": rec.get("hs_name"),
                    "hs_city": rec.get("hs_city"),
                    "hs_state": rec.get("hs_state"),
                    "suggestion_rank": rank,
                    "suggestion_score": round(score, 4),
                    "school_id": cand.get("school_id"),
                    "school_name": cand.get("school_name"),
                    "school_street": cand.get("street"),
                    "school_city": cand.get("city"),
                    "school_state": cand.get("state"),
                    "school_zip": cand.get("zip"),
                    "school_county_name": cand.get("county_name"),
                }
            )

    if not out_rows:
        return pl.DataFrame(
            schema={
                "review_id": pl.Int64,
                "bioguide": pl.Utf8,
                "politician_name": pl.Utf8,
                "hs_name": pl.Utf8,
                "hs_city": pl.Utf8,
                "hs_state": pl.Utf8,
                "suggestion_rank": pl.Int64,
                "suggestion_score": pl.Float64,
                "school_id": pl.Utf8,
                "school_name": pl.Utf8,
                "school_street": pl.Utf8,
                "school_city": pl.Utf8,
                "school_state": pl.Utf8,
                "school_zip": pl.Utf8,
                "school_county_name": pl.Utf8,
            }
        )

    return pl.DataFrame(out_rows).sort(["review_id", "suggestion_rank"])


def display_suggestions_summary(df_suggestions: pl.DataFrame) -> None:
    """Display summary statistics of no_match suggestions."""
    print("\n=== No-Match Suggestions Summary ===")
    print(f"Total suggestion rows: {len(df_suggestions)}")
    
    # Group by row_id to get number of politicians with suggestions
    politicians_with_suggestions = df_suggestions.select("review_id").unique().height
    print(f"Unique politicians: {politicians_with_suggestions}")
    
    # Average suggestions per politician
    avg_suggestions = len(df_suggestions) / politicians_with_suggestions
    print(f"Avg suggestions per politician: {avg_suggestions:.2f}")
    
    # Score distribution
    print("\nScore distribution:")
    score_stats = df_suggestions.select("suggestion_score").describe()
    print(score_stats)
    
    # High confidence (>= 0.85)
    high_conf = df_suggestions.filter(pl.col("suggestion_score") >= 0.85).height
    print(f"\nHigh confidence suggestions (≥0.85): {high_conf}")
    
    # Medium confidence (0.75-0.85)
    med_conf = df_suggestions.filter((pl.col("suggestion_score") >= 0.75) & (pl.col("suggestion_score") < 0.85)).height
    print(f"Medium confidence suggestions (0.75-0.85): {med_conf}")
    
    # Low confidence (0.72-0.75)
    low_conf = df_suggestions.filter((pl.col("suggestion_score") >= 0.72) & (pl.col("suggestion_score") < 0.75)).height
    print(f"Low confidence suggestions (0.72-0.75): {low_conf}")


def display_suggestions_by_politician(df_suggestions: pl.DataFrame, limit: int = 20) -> None:
    """Display suggestions grouped by politician."""
    print("\n=== Sample Suggestions (First 20 politicians) ===")
    
    # Group by row_id and display top-3 suggestions per politician
    grouped = df_suggestions.group_by("review_id").agg([
        pl.col("bioguide").first(),
        pl.col("politician_name").first(),
        pl.col("hs_name").first(),
        pl.col("hs_city").first(),
        pl.col("hs_state").first(),
        pl.col("school_name").alias("suggested_schools"),
        pl.col("suggestion_score").alias("suggestion_scores"),
    ])
    
    for i, row in enumerate(grouped.head(limit).iter_rows(named=True)):
        row_id = row["review_id"]
        print(
            f"\nRow {row_id} | {row['bioguide']} | {row.get('politician_name', '')} | "
            f"{row['hs_name']}, {row['hs_city']}, {row['hs_state']}"
        )
        
        # Get all suggestions for this politician
        suggestions = df_suggestions.filter(pl.col("review_id") == row_id).sort("suggestion_rank")
        if suggestions.height == 0 or suggestions.select(pl.col("suggestion_score").is_null().all()).item():
            print("  No suggestions available.")
            continue
        for sugg in suggestions.iter_rows(named=True):
            rank = sugg["suggestion_rank"]
            school = sugg["school_name"]
            score = sugg["suggestion_score"]
            city = sugg["school_city"]
            state = sugg["school_state"]
            if score is None:
                print(f"  {rank}. {school} ({city}, {state}) | Score: N/A")
            else:
                print(f"  {rank}. {school} ({city}, {state}) | Score: {score:.4f}")


def export_review_csv(df_suggestions: pl.DataFrame, output_path: str) -> None:
    """Export a review-ready CSV without longitude/latitude columns."""
    review_df = df_suggestions
    review_df.write_csv(output_path)
    print(f"✓ Exported review CSV to {output_path}")


def export_suggestions_by_confidence(df_suggestions: pl.DataFrame, output_dir: str) -> None:
    """Export suggestions grouped by confidence level."""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    export_columns = [col for col in df_suggestions.columns if col not in {"school_lat", "school_lon"}]
    
    # High confidence
    high = df_suggestions.filter(pl.col("suggestion_score") >= 0.85).select(export_columns)
    if len(high) > 0:
        high.write_csv(str(output_path / "suggestions_high_confidence.csv"))
        print(f"✓ Exported {len(high)} high-confidence suggestions to suggestions_high_confidence.csv")
    
    # Medium confidence
    med = df_suggestions.filter((pl.col("suggestion_score") >= 0.75) & (pl.col("suggestion_score") < 0.85)).select(export_columns)
    if len(med) > 0:
        med.write_csv(str(output_path / "suggestions_medium_confidence.csv"))
        print(f"✓ Exported {len(med)} medium-confidence suggestions to suggestions_medium_confidence.csv")
    
    # Low confidence
    low = df_suggestions.filter((pl.col("suggestion_score") >= 0.72) & (pl.col("suggestion_score") < 0.75)).select(export_columns)
    if len(low) > 0:
        low.write_csv(str(output_path / "suggestions_low_confidence.csv"))
        print(f"✓ Exported {len(low)} low-confidence suggestions to suggestions_low_confidence.csv")


def main():
    parser = argparse.ArgumentParser(
        description="Review no_match suggestions from the politician high school matching pipeline."
    )
    parser.add_argument(
        "--suggestions",
        type=str,
        default="01_data/intermediate/politicians_hs_no_match_suggestions.csv",
        help="Path to the no_match suggestions CSV",
    )
    parser.add_argument(
        "--matched",
        type=str,
        default="01_data/intermediate/politicians_hs_school_matched.csv",
        help="Path to the matched results CSV",
    )
    parser.add_argument(
        "--export-review-csv",
        action="store_true",
        help="Export a review-ready CSV with politician names and without lat/lon.",
    )
    parser.add_argument(
        "--review-output",
        type=str,
        default="01_data/intermediate/politicians_hs_no_match_suggestions_review.csv",
        help="Path for the review-ready CSV output.",
    )
    parser.add_argument(
        "--export-by-confidence",
        action="store_true",
        help="Export suggestions grouped by confidence level to separate CSVs",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="01_data/intermediate",
        help="Output directory for confidence-grouped CSVs",
    )
    
    args = parser.parse_args()
    
    print("Loading suggestions...")
    df_suggestions = load_suggestions(args.suggestions)
    
    print("Loading matched results...")
    df_matched = load_matched_results(args.matched)

    root = project_root()
    path_hs_ref = root / "01_data/intermediate/high_school/hs_all_clean.csv"
    df_hs_ref = load_school_reference(str(path_hs_ref))

    df_no_match = get_current_no_match_rows(df_matched)
    df_review = generate_no_match_suggestions(df_no_match, df_hs_ref)
    
    # Display summary
    display_suggestions_summary(df_review)
    
    # Display sample suggestions
    display_suggestions_by_politician(df_review)

    if args.export_review_csv:
        export_review_csv(df_review, args.review_output)
    
    # Export by confidence if requested
    if args.export_by_confidence:
        print("\n=== Exporting by Confidence Level ===")
        export_suggestions_by_confidence(df_review, args.output_dir)
    
    print("\nDone!")


if __name__ == "__main__":
    main()
